# Generated by Django 6.0.2 on 2026-02-12 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='knowledge_docs/%Y/%m/%d/')),
                ('file_size', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('embedding_model', models.CharField(choices=[('gemini-2.5-flash-embed', 'Gemini 2.5 Flash Embedding'), ('text-embedding-004', 'Google Text Embedding'), ('text-embedding-ada-002', 'OpenAI Ada')], default='gemini-2.5-flash-embed', max_length=100)),
                ('chunk_size', models.IntegerField(default=1000)),
                ('chunk_overlap', models.IntegerField(default=200)),
                ('document_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='knowledge_collections', to='agent_registry.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('embedding_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.document')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgecollection')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgecollection'),
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('query_embedding_id', models.CharField(blank=True, max_length=255)),
                ('retrieved_chunks', models.JSONField(default=list)),
                ('relevance_scores', models.JSONField(default=list)),
                ('response', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('retrieval_time_ms', models.IntegerField(default=0)),
                ('generation_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_queries', to='agent_registry.agent')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.knowledgecollection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgecollection',
            index=models.Index(fields=['owner', 'name'], name='knowledge_b_owner_i_03d2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['collection', 'document'], name='knowledge_b_collect_3ab0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['agent', 'created_at'], name='knowledge_b_agent_i_00ba22_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['collection', 'created_at'], name='knowledge_b_collect_cc85d4_idx'),
        ),
    ]
