# Generated by Django 6.0.2 on 2026-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knowledgecollection',
            name='embedding_model',
            field=models.CharField(choices=[('text-embedding-004', 'Google Text Embedding 004'), ('text-embedding-ada-002', 'OpenAI Ada v2')], default='text-embedding-004', max_length=100),
        ),
    ]
