# Generated by Django 6.0.2 on 2026-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_document_chunk_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecollection',
            name='embedding_model',
            field=models.CharField(choices=[('models/gemini-embedding-001', 'Gemini Embedding 001')], default='models/gemini-embedding-001', max_length=100),
        ),
    ]
