# Generated by Django 5.2.11 on 2026-05-25 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, choices=[('startup', 'Startup (1–10)'), ('smb', 'SMB (11–100)'), ('mid_market', 'Mid-market (101–1000)'), ('enterprise', 'Enterprise (1000+)')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('salesforce_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_accounts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('converted', 'Converted')], default='new', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('salesforce_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_leads', to='ops_core.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_leads', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('probability', models.IntegerField(default=0)),
                ('hubspot_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('salesforce_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_opportunities', to='ops_core.account')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_opportunities', to='ops_core.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_opportunities', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('lead_sync', 'Lead Sync'), ('ticket_sync', 'Ticket Sync'), ('opportunity_sync', 'Opportunity Sync'), ('account_sync', 'Account Sync'), ('webhook_dispatch', 'Webhook Dispatch'), ('email_dispatch', 'Email Dispatch'), ('campaign', 'Campaign')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('dead', 'Dead — max retries exceeded')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_queue_items', to='projects.project')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('phone', 'Phone'), ('web', 'Web'), ('slack', 'Slack')], default='email', max_length=20)),
                ('zendesk_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('intercom_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_tickets', to='ops_core.account')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_tickets', to='ops_core.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_tickets', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('meeting', 'Meeting'), ('note', 'Note'), ('demo', 'Demo'), ('trial', 'Trial'), ('chat', 'Chat')], max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_touchpoints', to='ops_core.account')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_touchpoints', to='ops_core.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_touchpoints', to='projects.project')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_touchpoints', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oc_touchpoints', to='ops_core.ticket')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['project', 'name'], name='ops_core_ac_project_2e33fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project', 'status'], name='ops_core_le_project_525367_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project', 'email'], name='ops_core_le_project_5143f0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['project', 'stage'], name='ops_core_op_project_6afdca_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['project', 'status'], name='ops_core_qu_project_d73972_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['status', 'scheduled_at'], name='ops_core_qu_status_1109c9_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['next_retry_at'], name='ops_core_qu_next_re_a2d565_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'status'], name='ops_core_ti_project_991d44_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'priority'], name='ops_core_ti_project_146793_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['project', 'type'], name='ops_core_to_project_9ac555_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['project', 'occurred_at'], name='ops_core_to_project_4c8856_idx'),
        ),
    ]
