# Generated by Django 5.2.11 on 2026-05-25 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops_core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='projects.project'),
        ),
        migrations.AddField(
            model_name='lead',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='ops_core.account'),
        ),
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='projects.project'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='ops_core.account'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='ops_core.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='projects.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ops_core.account'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ops_core.lead'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='ops_core.account'),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='ops_core.lead'),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='projects.project'),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_touchpoints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='ops_core.ticket'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['project', 'name'], name='ops_core_ac_project_2e33fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project', 'status'], name='ops_core_le_project_525367_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project', 'email'], name='ops_core_le_project_5143f0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['project', 'stage'], name='ops_core_op_project_6afdca_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['project', 'status'], name='ops_core_qu_project_d73972_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['status', 'scheduled_at'], name='ops_core_qu_status_1109c9_idx'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['next_retry_at'], name='ops_core_qu_next_re_a2d565_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'status'], name='ops_core_ti_project_991d44_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'priority'], name='ops_core_ti_project_146793_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['project', 'type'], name='ops_core_to_project_9ac555_idx'),
        ),
        migrations.AddIndex(
            model_name='touchpoint',
            index=models.Index(fields=['project', 'occurred_at'], name='ops_core_to_project_4c8856_idx'),
        ),
    ]
