# Generated by Django 5.2.11 on 2026-05-16 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_gateway", "0002_add_auth_workspace_llm_beta_models"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="betainvitecode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="betatesterprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="waitlistentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("onboarding_step", models.CharField(default="welcome", max_length=50)),
                (
                    "hitl_level",
                    models.CharField(
                        choices=[
                            ("strict", "Strict — approve every external action"),
                            ("standard", "Standard — approve high-stakes only"),
                            ("lenient", "Lenient — log only, no blocking"),
                            ("off", "Off — fully autonomous"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "hitl_cost_threshold",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("monthly_token_budget", models.IntegerField(default=50000)),
                ("notify_on_approval", models.BooleanField(default=True)),
                ("notify_on_failure", models.BooleanField(default=True)),
                ("notify_on_budget", models.BooleanField(default=True)),
                ("notify_in_app", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for_users",
                        to="agent_gateway.workspace",
                    ),
                ),
            ],
        ),
    ]
