# Generated by Django 5.2.11 on 2026-05-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="account",
            new_name="ops_account_owner_i_699102_idx",
            old_name="ops_account_owner_lifecycle_idx",
        ),
        migrations.RenameIndex(
            model_name="account",
            new_name="ops_account_externa_03e59e_idx",
            old_name="ops_account_provider_external_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="ops_lead_owner_i_04d138_idx",
            old_name="ops_lead_owner_status_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="ops_lead_source_86ba48_idx",
            old_name="ops_lead_source_status_idx",
        ),
        migrations.RenameIndex(
            model_name="lead",
            new_name="ops_lead_externa_5bfbe9_idx",
            old_name="ops_lead_provider_external_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="ops_opportu_owner_i_bb624e_idx",
            old_name="ops_opport_owner_stage_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunity",
            new_name="ops_opportu_externa_c0f1b2_idx",
            old_name="ops_opport_provider_external_idx",
        ),
        migrations.RenameIndex(
            model_name="queueitem",
            new_name="ops_queueit_owner_i_81c587_idx",
            old_name="ops_queue_owner_status_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="queueitem",
            new_name="ops_queueit_status_a348ef_idx",
            old_name="ops_queue_status_next_idx",
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="ops_ticket_owner_i_dc01be_idx",
            old_name="ops_ticket_owner_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="ops_ticket_channel_e43735_idx",
            old_name="ops_ticket_channel_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="ticket",
            new_name="ops_ticket_externa_d444be_idx",
            old_name="ops_ticket_provider_external_idx",
        ),
        migrations.RenameIndex(
            model_name="touchpoint",
            new_name="ops_touchpo_owner_i_608185_idx",
            old_name="ops_touch_owner_kind_dir_idx",
        ),
        migrations.RenameIndex(
            model_name="touchpoint",
            new_name="ops_touchpo_externa_e2332c_idx",
            old_name="ops_touch_provider_external_idx",
        ),
    ]
