# Generated by Django 5.2.11 on 2026-05-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ops",
            "0002_rename_ops_account_owner_lifecycle_idx_ops_account_owner_i_699102_idx_and_more",
        ),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queue_items",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="touchpoint",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="touchpoints",
                to="projects.project",
            ),
        ),
    ]
