apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aos-chroma-pvc
  namespace: aos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aos-media-pvc
  namespace: aos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
