# Generated by Django 6.0.2 on 2026-02-23 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_month_spend', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('alert_threshold_percentage', models.IntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='agent_registry.agent')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='billing.departmentcostcenter')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('compute_time_ms', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='agent_registry.agent')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='billing.departmentcostcenter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='billing_usa_agent_i_414d95_idx'), models.Index(fields=['department', 'created_at'], name='billing_usa_departm_8b4d3d_idx')],
            },
        ),
    ]
