# Generated by Django 5.2.11 on 2026-04-16 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agent_registry", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwarmAgentManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("swarm_name", models.CharField(max_length=255, unique=True)),
                (
                    "source_category",
                    models.CharField(
                        blank=True,
                        help_text="Swarm source category, e.g. 'sales', 'engineering', 'product'",
                        max_length=100,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to the agent .md definition file",
                        max_length=500,
                    ),
                ),
                (
                    "preferred_engine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("generic", "Generic CLI Engine"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "raw_markdown",
                    models.TextField(
                        blank=True,
                        help_text="Full content of the agent's .md definition file",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_version",
                    models.CharField(
                        blank=True,
                        help_text="swarm.config.json version at time of last sync",
                        max_length=50,
                    ),
                ),
                (
                    "aos_agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swarm_manifest",
                        to="agent_registry.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["source_category", "swarm_name"],
            },
        ),
        migrations.CreateModel(
            name="SwarmExecutionContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "swarm_agent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Swarm agent identifier, e.g. 'sales-account-strategist'",
                        max_length=255,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("claude", "Claude (Anthropic)"),
                            ("gemini", "Gemini (Google)"),
                            ("generic", "Generic CLI Engine"),
                        ],
                        default="claude",
                        max_length=20,
                    ),
                ),
                (
                    "workflow_phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("questionnaire", "Questionnaire"),
                            ("planner", "Planner"),
                            ("execute", "Execute"),
                            ("debug", "Debug"),
                            ("ship", "Ship"),
                            ("scout", "Scout"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("dev", "Development"),
                            ("staging", "Staging"),
                            ("prod", "Production"),
                        ],
                        default="dev",
                        max_length=10,
                    ),
                ),
                (
                    "task_summary",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the task dispatched to this agent",
                    ),
                ),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                (
                    "policy_decision",
                    models.CharField(
                        blank=True,
                        help_text="allow | deny | escalate — set after AOS policy evaluation",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("policy_reason", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aos_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="AOS Agent record corresponding to the swarm agent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="swarm_executions",
                        to="agent_registry.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["swarm_agent_name", "created_at"],
                        name="swarm_bridg_swarm_a_73f037_idx",
                    ),
                    models.Index(
                        fields=["policy_decision", "created_at"],
                        name="swarm_bridg_policy__120814_idx",
                    ),
                    models.Index(
                        fields=["environment", "created_at"],
                        name="swarm_bridg_environ_27135a_idx",
                    ),
                ],
            },
        ),
    ]
