# Generated by Django 5.2.11 on 2026-05-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_registry", "0005_remove_agenttrustpolicy_unique_trust_pair_and_more"),
        ("swarm_bridge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="swarmexecutioncontext",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("denied", "Denied by policy"),
                ],
                db_index=True,
                default="pending",
                help_text="Run lifecycle status — drives Observe stream and replay endpoint",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="swarmexecutioncontext",
            index=models.Index(
                fields=["status", "created_at"], name="swarm_bridg_status_25066f_idx"
            ),
        ),
    ]
