# Generated by Django 5.2.11 on 2026-05-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("swarm_bridge", "0003_swarmexecutioncontext_run_lines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swarmexecutioncontext",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="swarm_executions",
                to="projects.project",
            ),
        ),
    ]
