# Generated by Django 6.0.2 on 2026-02-12 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list, help_text="List of permission strings, e.g. ['tools:read', 'agents:create']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('agent_type', models.CharField(choices=[('EXECUTIVE', 'Executive Agent'), ('FUNCTIONAL', 'Functional Agent'), ('SUB_AGENT', 'Sub-Agent'), ('OBSERVER', 'Observer / Auditor Agent')], default='FUNCTIONAL', max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('identity_key', models.CharField(help_text='Unique API token / cryptographic identity for the agent', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('ERRORED', 'Errored')], default='RUNNING', max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Arbitrary metadata / configuration for the agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns/created this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='agents', to='agent_registry.role')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='agent_regis_owner_i_1083e2_idx'), models.Index(fields=['identity_key'], name='agent_regis_identit_a410d5_idx')],
            },
        ),
    ]
