# Generated by Django 5.2.11 on 2026-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_registry", "0002_agent_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="source",
            field=models.CharField(
                choices=[("AOS", "AOS Native"), ("SWARM", "Agent Swarm")],
                default="AOS",
                help_text="Origin of this agent: AOS-native or imported from Agent Swarm",
                max_length=10,
            ),
        ),
    ]
