# Generated by Django 5.2.11 on 2026-05-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agent_registry", "0004_agent_environment_trustpolicy"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agenttrustpolicy",
            name="unique_trust_pair",
        ),
        migrations.AlterUniqueTogether(
            name="agenttrustpolicy",
            unique_together={("source_agent", "target_agent")},
        ),
    ]
