# Generated by Django 6.0.2 on 2026-02-12 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(help_text='Field to evaluate (e.g., request.method, resource.type)', max_length=100)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('in', 'In List'), ('not_in', 'Not In List'), ('between', 'Between'), ('regex', 'Matches Regex')], max_length=20)),
                ('value', models.JSONField(help_text='Value to compare against')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('resources', models.JSONField(default=list, help_text="List of resources this policy applies to (e.g., ['tool:crm', 'agent:execute'])")),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny'), ('AUDIT', 'Audit Only'), ('ESCALATE', 'Require Approval')], default='DENY', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_calls', models.IntegerField(blank=True, help_text='Maximum number of times this policy can be applied', null=True)),
                ('calls_made', models.IntegerField(default=0)),
                ('risk_level', models.IntegerField(default=0, help_text='0 = Low Risk, 100 = Critical Risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agents', models.ManyToManyField(blank=True, related_name='policies', to='agent_registry.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, related_name='policies', to='agent_registry.role')),
                ('conditions', models.ManyToManyField(blank=True, related_name='policies', to='policy_engine.policycondition')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_registry.agent')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='policy_engine.policy')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent_registry.role')),
            ],
            options={
                'unique_together': {('policy', 'agent'), ('policy', 'role')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('request_data', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied'), ('AUDIT', 'Audited'), ('ESCALATE', 'Escalated')], max_length=20)),
                ('reason', models.TextField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_logs', to='agent_registry.agent')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy_engine.policy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='policy_engi_agent_i_438e1d_idx'), models.Index(fields=['decision', 'created_at'], name='policy_engi_decisio_5a579d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['is_active', 'effect'], name='policy_engi_is_acti_fafa7e_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['valid_from', 'valid_until'], name='policy_engi_valid_f_8924bc_idx'),
        ),
    ]
