# Generated by Django 5.2.11 on 2026-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0002_workspace_policy_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='effect',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny'), ('AUDIT', 'Audit Only'), ('ESCALATE', 'Require Approval'), ('THROTTLE', 'Throttle')], default='DENY', max_length=20),
        ),
        migrations.AlterField(
            model_name='policyauditlog',
            name='decision',
            field=models.CharField(choices=[('ALLOW', 'Allowed'), ('DENY', 'Denied'), ('AUDIT', 'Audited'), ('ESCALATE', 'Escalated'), ('THROTTLE', 'Throttled')], max_length=20),
        ),
    ]
