# Generated by Django 5.2.11 on 2026-05-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_engine", "0003_alter_policy_effect_alter_policyauditlog_decision"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="policyauditlog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policy_audit_logs",
                to="projects.project",
            ),
        ),
    ]
