# Generated by Django 6.0.2 on 2026-02-12 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('GEMINI', 'Google Gemini'), ('CLAUDE', 'Anthropic Claude'), ('OPENAI', 'OpenAI GPT'), ('MISTRAL', 'Mistral AI'), ('LLAMA', 'Meta Llama'), ('CUSTOM', 'Custom LLM')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_base', models.URLField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('top_p', models.FloatField(default=0.95)),
                ('frequency_penalty', models.FloatField(default=0.0)),
                ('presence_penalty', models.FloatField(default=0.0)),
                ('supports_tools', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('max_context_length', models.IntegerField(default=128000)),
                ('cost_per_1k_tokens_input', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('cost_per_1k_tokens_output', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('rate_limit_requests_per_minute', models.IntegerField(default=60)),
                ('rate_limit_tokens_per_minute', models.IntegerField(default=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='ACTIVE', max_length=20)),
                ('total_tokens_input', models.IntegerField(default=0)),
                ('total_tokens_output', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agent_registry.agent')),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_intelligence.llmconfig')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_type', models.CharField(choices=[('REACT', 'ReAct Agent'), ('PLAN_EXECUTE', 'Plan-and-Execute'), ('MULTI_AGENT', 'Multi-Agent Supervisor'), ('CUSTOM', 'Custom Graph')], default='REACT', max_length=50)),
                ('memory_type', models.CharField(choices=[('BUFFER', 'Conversation Buffer'), ('BUFFER_WINDOW', 'Window Buffer'), ('SUMMARY', 'Summary Memory'), ('VECTOR', 'Vector Store Memory'), ('NONE', 'No Memory')], default='BUFFER_WINDOW', max_length=50)),
                ('memory_window', models.IntegerField(default=10)),
                ('tools_enabled', models.JSONField(default=list)),
                ('rag_enabled', models.BooleanField(default=False)),
                ('rag_collection', models.CharField(blank=True, max_length=100)),
                ('rag_top_k', models.IntegerField(default=5)),
                ('max_iterations', models.IntegerField(default=10)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capability', to='agent_registry.agent')),
                ('primary_llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_agents', to='agent_intelligence.llmconfig')),
                ('reasoning_llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_for_agents', to='agent_intelligence.llmconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('AGENT', 'Agent'), ('TOOL', 'Tool')], max_length=10)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tokens', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_intelligence.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('parameters_schema', models.JSONField(default=dict)),
                ('tool_type', models.CharField(choices=[('API', 'HTTP API Call'), ('FUNCTION', 'Python Function'), ('DATABASE', 'Database Query'), ('WORKFLOW', 'Workflow Trigger')], max_length=50)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_method', models.CharField(blank=True, max_length=10)),
                ('api_headers', models.JSONField(default=dict)),
                ('function_path', models.CharField(blank=True, max_length=500)),
                ('required_permissions', models.JSONField(default=list)),
                ('rate_limit', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='llmconfig',
            index=models.Index(fields=['provider', 'model_name'], name='agent_intel_provide_947241_idx'),
        ),
        migrations.AddIndex(
            model_name='llmconfig',
            index=models.Index(fields=['is_active'], name='agent_intel_is_acti_f64699_idx'),
        ),
    ]
