# Generated by Django 6.0.2 on 2026-02-23 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_intelligence', '0001_initial'),
        ('agent_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcapability',
            name='sub_agents',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to='agent_registry.agent'),
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent_registry.agent')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='agent_intelligence.workflowtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
