# Generated by Django 5.2.11 on 2026-02-23 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_intelligence', '0002_agentcapability_sub_agents_workflowtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=100)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(default=0)),
                ('is_loop', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='agent_intelligence.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
