# Generated by Django 5.2.11 on 2026-05-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_intelligence", "0005_pendingaction_escalated_status"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="pendingaction",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_actions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="tracestep",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trace_steps",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="workflowtask",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_tasks",
                to="projects.project",
            ),
        ),
    ]
