# Generated by Django 6.0.4 on 2026-06-01 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("objective", models.TextField(blank=True, default="")),
                ("audience", models.CharField(blank=True, default="", max_length=255)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("budget", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SCHEDULED", "Scheduled"), ("PUBLISHING", "Publishing"), ("LIVE", "Live"), ("MEASURING", "Measuring"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="DRAFT", max_length=20)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("content_brief", models.TextField(blank=True, default="")),
                ("performance_summary", models.JSONField(blank=True, default=dict)),
                ("next_action_suggestions", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="marketing_campaigns", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="projects.project")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ContentCalendarItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("platform", models.CharField(choices=[("instagram", "Instagram"), ("tiktok", "TikTok"), ("linkedin", "LinkedIn"), ("twitter", "X/Twitter"), ("facebook", "Facebook"), ("other", "Other")], default="instagram", max_length=30)),
                ("caption", models.TextField(blank=True, default="")),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SCHEDULED", "Scheduled"), ("QUEUED", "Queued"), ("PUBLISHING", "Publishing"), ("PUBLISHED", "Published"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], default="DRAFT", max_length=20)),
                ("uploadpost_request_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("external_post_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("publish_result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_items", to="marketing.campaign")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="content_calendar_items", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="content_calendar_items", to="projects.project")),
            ],
            options={"ordering": ["scheduled_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="CampaignMetric",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("reach", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("comments", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("saves", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                ("spend", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("calendar_item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="metrics", to="marketing.contentcalendaritem")),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="marketing.campaign")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="campaign_metrics", to="projects.project")),
            ],
            options={"ordering": ["-captured_at"]},
        ),
        migrations.AddIndex(model_name="campaign", index=models.Index(fields=["project", "status"], name="marketing_c_project_9f1e23_idx")),
        migrations.AddIndex(model_name="campaign", index=models.Index(fields=["owner", "status"], name="marketing_c_owner_i_c10119_idx")),
        migrations.AddIndex(model_name="contentcalendaritem", index=models.Index(fields=["project", "status"], name="marketing_c_project_cdf2ff_idx")),
        migrations.AddIndex(model_name="contentcalendaritem", index=models.Index(fields=["campaign", "status"], name="marketing_c_campaig_0b23c1_idx")),
        migrations.AddIndex(model_name="contentcalendaritem", index=models.Index(fields=["scheduled_at", "status"], name="marketing_c_schedul_006cbc_idx")),
        migrations.AddIndex(model_name="campaignmetric", index=models.Index(fields=["project", "captured_at"], name="marketing_c_project_62406f_idx")),
        migrations.AddIndex(model_name="campaignmetric", index=models.Index(fields=["campaign", "captured_at"], name="marketing_c_campaig_b546ea_idx")),
    ]
